# file: roles/webtier/tasks/dotenv.yml
- name: Check if .env template exists
  tags: dotenv
  local_action: stat path=dotenv_templates/{{ inventory_hostname }}.{{ item.key }}.j2
  vars:
     ansible_become: no
  with_dict: "{{ virtualhosts }}"
  register: dotenv_file

- name: Create node spesific .env file  
  tags: dotenv
  template: src=dotenv_templates/{{ inventory_hostname }}.{{ item.key }}.j2 dest=/var/www/{{ item.key }}/.env
  with_dict: "{{ virtualhosts }}"  
  when: dotenv_file.results[0].stat.exists == True
