# file: roles/webtier/tasks/php.yml
- name: Install PHP and extensions
  yum: name={{ item }} state=installed enablerepo=epel,remi,remi-php71
  tags: php
  with_items:
    - php
    - php-zip
    - php-openssl
    - php-pdo
    - php-mbstring
    - php-tokenizer
    - php-xml
    - php-mysqlnd
    - php-opcache
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

- name: Install PHP and extensions
  apt: name={{ item }} state=installed update_cache=yes
  tags: php
  with_items:
    - php7.1
    - php7.1-zip
    - php7.1-pdo
    - php7.1-mbstring
    - php7.1-tokenizer
    - php7.1-xml
    - php7.1-mysqlnd
    - php7.1-opcache
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
